/*
 * JS for mainpage generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'e73f7bda-f657-47be-96f4-5c6b12a435b3';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "mainpage",
    "location": "mainpage.html"
}, {
    "name": "start",
    "location": "start.html"
}];

function mainpage_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_13': 'mainpage_mobilebutton_13',
        'mobilebutton_14': 'mainpage_mobilebutton_14',
        'html_10': 'mainpage_html_10',
        'mobilelabel_11': 'mainpage_mobilelabel_11',
        'mobilelabel_12': 'mainpage_mobilelabel_12',
        'mobilegroupedbuttons_3': 'mainpage_mobilegroupedbuttons_3',
        'mobilebutton_4': 'mainpage_mobilebutton_4',
        'mobilebutton_5': 'mainpage_mobilebutton_5',
        'mobilebutton_6': 'mainpage_mobilebutton_6',
        'mobilebutton_7': 'mainpage_mobilebutton_7',
        'mobilebutton_8': 'mainpage_mobilebutton_8',
        'mobilebutton_9': 'mainpage_mobilebutton_9'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["mainpage_advertise_page_onsuccess_mapping_0"] = {
        "homeScreen": "mainpage",
        "directions": [

        {
            "from_name": "advertise_page",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "mainpage",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['html']",
                "target": "$['html_10:rawHtml']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["mainpage_advertise_page_onbeforesend_mapping_0"] = {
        "homeScreen": "mainpage",
        "directions": [

        {
            "from_name": "token",
            "from_type": "LOCAL_STORAGE",

            "to_name": "advertise_page",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "page": "advertise"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['CAMEN-API-KEY']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["mainpage_privacy_page_onbeforesend_mapping_0"] = {
        "homeScreen": "mainpage",
        "directions": [

        {
            "from_name": "token",
            "from_type": "LOCAL_STORAGE",

            "to_name": "privacy_page",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "page": "privacy"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['CAMEN-API-KEY']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["mainpage_privacy_page_onsuccess_mapping_0"] = {
        "homeScreen": "mainpage",
        "directions": [

        {
            "from_name": "privacy_page",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "mainpage",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['html']",
                "target": "$['html_10:rawHtml']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["mainpage_feedback_page_onsuccess_mapping_0"] = {
        "homeScreen": "mainpage",
        "directions": [

        {
            "from_name": "feedback_page",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "mainpage",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['html']",
                "target": "$['html_10:rawHtml']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["mainpage_feedback_page_onbeforesend_mapping_0"] = {
        "homeScreen": "mainpage",
        "directions": [

        {
            "from_name": "token",
            "from_type": "LOCAL_STORAGE",

            "to_name": "feedback_page",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "page": "feedback"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['CAMEN-API-KEY']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["mainpage_contact_page_onsuccess_mapping_0"] = {
        "homeScreen": "mainpage",
        "directions": [

        {
            "from_name": "contact_page",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "mainpage",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['html']",
                "target": "$['html_10:rawHtml']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["mainpage_contact_page_onbeforesend_mapping_0"] = {
        "homeScreen": "mainpage",
        "directions": [

        {
            "from_name": "token",
            "from_type": "LOCAL_STORAGE",

            "to_name": "contact_page",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "page": "contact"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['CAMEN-API-KEY']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["mainpage_about_page_onbeforesend_mapping_0"] = {
        "homeScreen": "mainpage",
        "directions": [

        {
            "from_name": "token",
            "from_type": "LOCAL_STORAGE",

            "to_name": "about_page",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "page": "about"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['CAMEN-API-KEY']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["mainpage_about_page_onsuccess_mapping_0"] = {
        "homeScreen": "mainpage",
        "directions": [

        {
            "from_name": "about_page",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "mainpage",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['html']",
                "target": "$['html_10:rawHtml']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["mainpage_faq_page_onsuccess_mapping_0"] = {
        "homeScreen": "mainpage",
        "directions": [

        {
            "from_name": "faq_page",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "mainpage",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['html']",
                "target": "$['html_10:rawHtml']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["mainpage_faq_page_onbeforesend_mapping_0"] = {
        "homeScreen": "mainpage",
        "directions": [

        {
            "from_name": "token",
            "from_type": "LOCAL_STORAGE",

            "to_name": "faq_page",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "page": "faq"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['CAMEN-API-KEY']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["mainpage_gallery_page_onsuccess_mapping_0"] = {
        "homeScreen": "mainpage",
        "directions": [

        {
            "from_name": "gallery_page",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "mainpage",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['html']",
                "target": "$['html_10:rawHtml']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["mainpage_gallery_page_onbeforesend_mapping_0"] = {
        "homeScreen": "mainpage",
        "directions": [

        {
            "from_name": "token",
            "from_type": "LOCAL_STORAGE",

            "to_name": "gallery_page",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "page": "gallery"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['CAMEN-API-KEY']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.advertise_page = Apperyio.datasources.advertise_page = new Apperyio.DataSource(thisislifeapp_show_page, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["mainpage_advertise_page_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            $('[id="mainpage_panel_2"]').panel("close");

            Apperyio.refreshScreenFormElements("mainpage");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["mainpage_advertise_page_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.privacy_page = Apperyio.datasources.privacy_page = new Apperyio.DataSource(thisislifeapp_show_page, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["mainpage_privacy_page_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            $('[id="mainpage_panel_2"]').panel("close");

            Apperyio.refreshScreenFormElements("mainpage");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["mainpage_privacy_page_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.feedback_page = Apperyio.datasources.feedback_page = new Apperyio.DataSource(thisislifeapp_show_page, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["mainpage_feedback_page_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            $('[id="mainpage_panel_2"]').panel("close");

            Apperyio.refreshScreenFormElements("mainpage");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["mainpage_feedback_page_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.contact_page = Apperyio.datasources.contact_page = new Apperyio.DataSource(thisislifeapp_show_page, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["mainpage_contact_page_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            $('[id="mainpage_panel_2"]').panel("close");

            Apperyio.refreshScreenFormElements("mainpage");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["mainpage_contact_page_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.about_page = Apperyio.datasources.about_page = new Apperyio.DataSource(thisislifeapp_show_page, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["mainpage_about_page_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            $('[id="mainpage_panel_2"]').panel("close");

            Apperyio.refreshScreenFormElements("mainpage");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["mainpage_about_page_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.faq_page = Apperyio.datasources.faq_page = new Apperyio.DataSource(thisislifeapp_show_page, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["mainpage_faq_page_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            $('[id="mainpage_panel_2"]').panel("close");

            Apperyio.refreshScreenFormElements("mainpage");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["mainpage_faq_page_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.gallery_page = Apperyio.datasources.gallery_page = new Apperyio.DataSource(thisislifeapp_show_page, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["mainpage_gallery_page_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("mainpage");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["mainpage_gallery_page_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'mainpage';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var mainpage_onLoad = function() {
            mainpage_elementsExtraJS();

            if (localStorage.getItem('user_id') !== null) {

                Apperyio.navigateTo('mainpage', {});
            } else {
                Appery('mobilecollapsibleset_89').show();
            };
            try {
                gallery_page.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };

            mainpage_deviceEvents();
            mainpage_windowEvents();
            mainpage_elementsEvents();
        };

    // screen window events


    function mainpage_windowEvents() {

        $('#mainpage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#mainpage').on({
            pageshow: function(event) {
                try {
                    $a.c15r("mobilelabel_12", "set", "text", $a.storage["user_public_name"].get("$"))
                } catch (e) {
                    console.error(e)
                };
            },
            swipeleft: function(event) {
                $('[id="mainpage_panel_2"]').panel("close");
            },
            swiperight: function(event) {
                $('[id="mainpage_panel_2"]').panel("open");
            },
        });

    };

    // device events


    function mainpage_deviceEvents() {
        document.addEventListener("deviceready", function() {
            $(document).off('menubutton resume backbutton ').on({
                "menubutton": function(event) {
                    $('[id="mainpage_panel_2"]').panel("open");
                },
                "resume": function(event) {
                    if (localStorage.getItem('user_id') !== null) {

                        Apperyio.navigateTo('mainpage', {});
                    } else {
                        Appery('mobilecollapsibleset_89').show();
                    };
                },
                "backbutton": function(event) {
                    $('[id="mainpage_panel_2"]').panel("open");
                },
            });

        });
    };

    // screen elements extra js


    function mainpage_elementsExtraJS() {
        // screen (mainpage) extra code

    };

    // screen elements handler


    function mainpage_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#mainpage_mobileheader [name="mobilebutton_13"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    $('[id="mainpage_panel_2"]').panel("open");

                }
            },
        }, '#mainpage_mobileheader [name="mobilebutton_13"]');
        $(document).off("click", '#mainpage_mobileheader [name="mobilebutton_14"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        gallery_page.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#mainpage_mobileheader [name="mobilebutton_14"]');

        $(document).off("click", '#mainpage_panel_2 [name="mobilebutton_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        advertise_page.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#mainpage_panel_2 [name="mobilebutton_4"]');
        $(document).off("click", '#mainpage_panel_2 [name="mobilebutton_5"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        privacy_page.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#mainpage_panel_2 [name="mobilebutton_5"]');
        $(document).off("click", '#mainpage_panel_2 [name="mobilebutton_6"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        feedback_page.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#mainpage_panel_2 [name="mobilebutton_6"]');
        $(document).off("click", '#mainpage_panel_2 [name="mobilebutton_7"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        contact_page.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#mainpage_panel_2 [name="mobilebutton_7"]');
        $(document).off("click", '#mainpage_panel_2 [name="mobilebutton_8"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        about_page.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#mainpage_panel_2 [name="mobilebutton_8"]');
        $(document).off("click", '#mainpage_panel_2 [name="mobilebutton_9"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        faq_page.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#mainpage_panel_2 [name="mobilebutton_9"]');

    };

    $(document).off("pagebeforeshow", "#mainpage").on("pagebeforeshow", "#mainpage", function(event, ui) {
        Apperyio.CurrentScreen = "mainpage";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    mainpage_onLoad();
};

$(document).off("pagecreate", "#mainpage").on("pagecreate", "#mainpage", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    mainpage_js();
});