/*
 * JS for start generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'e73f7bda-f657-47be-96f4-5c6b12a435b3';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "mainpage",
    "location": "mainpage.html"
}, {
    "name": "start",
    "location": "start.html"
}];

function start_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilecollapsibleset_89': 'start_mobilecollapsibleset_89',
        'mobilecollapsblock_99': 'start_mobilecollapsblock_99',
        'Login': 'start_Login',
        'mobilecollapsblockcontent_101': 'start_mobilecollapsblockcontent_101',
        'loginUsername': 'start_loginUsername',
        'loginPassword': 'start_loginPassword',
        'loginButton': 'start_loginButton',
        'mobilecollapsblock_105': 'start_mobilecollapsblock_105',
        'Register': 'start_Register',
        'mobilecollapsblockcontent_107': 'start_mobilecollapsblockcontent_107',
        'registerUsername': 'start_registerUsername',
        'registerPassword': 'start_registerPassword',
        'registerPasswordC': 'start_registerPasswordC',
        'registerEmail': 'start_registerEmail',
        'registerPhone': 'start_registerPhone',
        'registerFirstname': 'start_registerFirstname',
        'registerLastname': 'start_registerLastname',
        'registerAge': 'start_registerAge',
        'registerSex': 'start_registerSex',
        'registerSexmale': 'start_registerSexmale',
        'registerSexfemale': 'start_registerSexfemale',
        'registerButton': 'start_registerButton',
        'mobilecollapsblock_127': 'start_mobilecollapsblock_127',
        'forgotPassword': 'start_forgotPassword',
        'mobilecollapsblockcontent_129': 'start_mobilecollapsblockcontent_129',
        'mobilelabel_132': 'start_mobilelabel_132',
        'passwordEmail': 'start_passwordEmail',
        'mobilebutton_133': 'start_mobilebutton_133',
        'recovery_container': 'start_recovery_container',
        'recovery_holder': 'start_recovery_holder',
        'mobilecollapsblockheader_155': 'start_mobilecollapsblockheader_155',
        'mobilecollapsblockcontent_156': 'start_mobilecollapsblockcontent_156',
        'recovery_secret_code': 'start_recovery_secret_code',
        'recovery_new_password': 'start_recovery_new_password',
        'recoverNow': 'start_recoverNow'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["start_loginService_onsuccess_mapping_0"] = {
        "homeScreen": "start",
        "directions": [

        {
            "from_name": "loginService",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "user_id",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['user_id']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "loginService",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "token",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['token']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "loginService",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "user_public_name",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['public_name']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["start_loginService_onbeforesend_mapping_0"] = {
        "homeScreen": "start",
        "directions": [

        {
            "from_name": "start",
            "from_type": "UI",

            "to_name": "loginService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "CAMEN-API-KEY": "thisislifeapp"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$['loginPassword:text']",
                "target": "$['parameters']['password']"

            },

            {

                "source": "$['loginUsername:text']",
                "target": "$['parameters']['username']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["start_signupService_onbeforesend_mapping_0"] = {
        "homeScreen": "start",
        "directions": [

        {
            "from_name": "start",
            "from_type": "UI",

            "to_name": "signupService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "CAMEN-API-KEY": "thisislifeapp"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$['registerUsername:text']",
                "target": "$['parameters']['registerUsername']"

            },

            {

                "source": "$['registerPassword:text']",
                "target": "$['parameters']['registerPassword']"

            },

            {

                "source": "$['registerEmail:text']",
                "target": "$['parameters']['registerEmail']"

            },

            {

                "source": "$['registerPhone:text']",
                "target": "$['parameters']['registerPhone']"

            },

            {

                "source": "$['registerFirstname:text']",
                "target": "$['parameters']['registerFirstname']"

            },

            {

                "source": "$['registerLastname:text']",
                "target": "$['parameters']['registerLastname']"

            },

            {

                "source": "$['registerAge:text']",
                "target": "$['parameters']['registerAge']"

            },

            {

                "source": "$['registerSex:selectedOption']",
                "target": "$['parameters']['registerSex']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["start_signupService_onsuccess_mapping_0"] = {
        "homeScreen": "start",
        "directions": [

        {
            "from_name": "signupService",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "user_id",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['user_id']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "signupService",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "token",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['token']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "signupService",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "user_public_name",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['public_name']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["start_forgotService_onbeforesend_mapping_0"] = {
        "homeScreen": "start",
        "directions": [

        {
            "from_name": "start",
            "from_type": "UI",

            "to_name": "forgotService",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "CAMEN-API-KEY": "thisislifeapp"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$['passwordEmail:text']",
                "target": "$['parameters']['email']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["start_forgotService_onsuccess_mapping_0"] = {
        "homeScreen": "start",
        "directions": []
    };

    Apperyio.mappings["start_recoverNow_onsuccess_mapping_0"] = {
        "homeScreen": "start",
        "directions": []
    };

    Apperyio.mappings["start_recoverNow_onbeforesend_mapping_0"] = {
        "homeScreen": "start",
        "directions": [

        {
            "from_name": "start",
            "from_type": "UI",

            "to_name": "recoverNow",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "CAMEN-API-KEY": "thisislifeapp"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$['recovery_secret_code:text']",
                "target": "$['parameters']['secret_code']"

            },

            {

                "source": "$['recovery_new_password:text']",
                "target": "$['parameters']['new_password']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.loginService = Apperyio.datasources.loginService = new Apperyio.DataSource(thisislifeapp_login_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["start_loginService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("start");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["start_loginService_onsuccess_mapping_0"]);
            Apperyio.navigateTo('mainpage', {
                transition: 'slidedown',
                reverse: false
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            alert(jqXHR.responseText);;
        }
    });

    window.signupService = Apperyio.datasources.signupService = new Apperyio.DataSource(thisislifeapp_signup_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["start_signupService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("start");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["start_signupService_onsuccess_mapping_0"]);
            Apperyio.navigateTo('mainpage', {
                transition: 'slidedown',
                reverse: false
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            alert(jqXHR.responseText);;
        }
    });

    window.forgotService = Apperyio.datasources.forgotService = new Apperyio.DataSource(thisislifeapp_forgot_pass, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["start_forgotService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("start");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["start_forgotService_onsuccess_mapping_0"]);
            toggle('start_recovery_container', 'mob', 'true');
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.recoverNow = Apperyio.datasources.recoverNow = new Apperyio.DataSource(thisislifeapp_recover_now, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["start_recoverNow_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("start");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["start_recoverNow_onsuccess_mapping_0"]);
            alert('Login with your new password');
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'start';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var start_onLoad = function() {
            start_elementsExtraJS();

            if (localStorage.getItem('user_id') !== null) {

                Apperyio.navigateTo('mainpage', {});
            } else {
                Appery('mobilecollapsibleset_89').show();
            };

            start_deviceEvents();
            start_windowEvents();
            start_elementsEvents();
        };

    // screen window events


    function start_windowEvents() {

        $('#start').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function start_deviceEvents() {
        document.addEventListener("deviceready", function() {

            if (localStorage.getItem('user_id') !== null) {

                Apperyio.navigateTo('mainpage', {});
            } else {
                Appery('mobilecollapsibleset_89').show();
            };
            $(document).off('resume ').on({
                "resume": function(event) {
                    if (localStorage.getItem('user_id') !== null) {

                        Apperyio.navigateTo('mainpage', {});
                    } else {
                        Appery('mobilecollapsibleset_89').show();
                    };
                },
            });

        });
    };

    // screen elements extra js


    function start_elementsExtraJS() {
        // screen (start) extra code

        /* mobilecollapsblock_99 */

        $("#start_mobilecollapsblock_99 .ui-collapsible-heading-toggle").attr("tabindex", "25");

        /* mobilecollapsblock_105 */

        $("#start_mobilecollapsblock_105 .ui-collapsible-heading-toggle").attr("tabindex", "25");

        /* mobilecollapsblock_127 */

        $("#start_mobilecollapsblock_127 .ui-collapsible-heading-toggle").attr("tabindex", "25");

        /* recovery_holder */

        $("#start_recovery_holder .ui-collapsible-heading-toggle").attr("tabindex", "48");

    };

    // screen elements handler


    function start_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#start_mobilecontainer [name="loginButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        loginService.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#start_mobilecontainer [name="loginButton"]');

        $(document).off("click", '#start_mobilecontainer [name="registerButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    console.log('is: ', is);
                    if ($.trim(Appery('registerUsername').val()) !== '' && is.string(Appery('registerUsername').val())) {
                        if (Appery('registerPassword').val() == Appery('registerPasswordC').val() && Appery('registerPassword').val() != '' && is.string(Appery('registerPassword').val())) {
                            if (Appery('registerEmail').val() !== '' && is.email(Appery('registerEmail').val())) {
                                if (!document.getElementsByName('registerEmail')[0].checkValidity || document.getElementsByName('registerEmail')[0].checkValidity()) {
                                    if (Appery('registerPhone').val() !== '') {
                                        if (Appery('registerFirstname').val() !== '' && is.string(Appery('registerFirstname').val())) {
                                            if (Appery('registerLastname').val() !== '' && is.string(Appery('registerLastname').val())) {
                                                if (Appery('registerAge').val() !== '') {
                                                    if (Appery('registerSex :radio:checked').val() !== '') {
                                                        signupService.execute({});
                                                    } else {
                                                        alert('Please enter your sex.');
                                                    }
                                                } else {
                                                    alert('Please enter your age.');
                                                }
                                            } else {
                                                alert('Please enter your last name.');
                                            }
                                        } else {
                                            alert('Please enter your first name.');
                                        }
                                    } else {
                                        alert('Please enter your phone.');
                                    }
                                } else {
                                    alert('Please enter a valid email.');
                                }
                            } else {
                                alert('Please enter your email.');
                            }
                        } else {
                            alert('Passwords don\'t match.');
                        }
                    } else {
                        alert('Please enter your username.');
                    };

                }
            },
        }, '#start_mobilecontainer [name="registerButton"]');

        $(document).off("click", '#start_mobilecontainer [name="mobilebutton_133"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    if (Appery('passwordEmail').val() != '' && is.email(Appery('passwordEmail').val())) {
                        forgotService.execute({});
                    } else {
                        alert('Please add valid email');
                    };

                }
            },
        }, '#start_mobilecontainer [name="mobilebutton_133"]');

        $(document).off("click", '#start_mobilecontainer [name="recoverNow"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        recoverNow.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#start_mobilecontainer [name="recoverNow"]');

    };

    $(document).off("pagebeforeshow", "#start").on("pagebeforeshow", "#start", function(event, ui) {
        Apperyio.CurrentScreen = "start";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    start_onLoad();
};

$(document).off("pagecreate", "#start").on("pagecreate", "#start", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    start_js();
});